swaglabs sucess
gadelrabee/cypress_automation pull request #1
Opened 2024-08-19 07:26 UTC by gadelrabee

2024-08-19 07:35 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#login-button").clear.click();
Please remove 'clear' in the login button.

2024-08-19 07:42 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#user-name").clear.type("standard_user");
The clear command should be followed by parentheses '()'. Please add the parenthesis.

2024-08-19 07:42 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#password").clear.type("secret_sauce");
The clear command should be followed by parentheses '()'. Please add the parenthesis.

2024-08-19 07:45 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#user-name").clear.type("standard_user123");
The clear command should be followed by parentheses '()'. Please add the parenthesis.

2024-08-19 07:45 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#password").clear.type("secret_sauce123");
The clear command should be followed by parentheses '()'. Please add the parenthesis.

2024-08-19 07:49 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +    it.skip('should not login with valid username and empty password', ()=>{
The text inside it block is incorrect. it should be 'empty username and valid password'

2024-08-19 07:49 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +    it.skip('should not login with valid username and empty password', ()=>{
The text inside it block is incorrect. it should be 'empty username and empty password'

2024-08-19 07:53 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get('#react-burger-menu-btn').click();
Please try to add assertions before clicking any buttons.

2024-08-19 07:53 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get('#logout_sidebar_link').click();
Please try to add assertions before clicking any buttons.

2024-08-19 07:57 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("input[name='login-button']").should('be.visible').and('not.be.disabled');
In line 168, 169, 170 there is no need to have click command.

2024-08-19 08:59 UTC, rtimalsina555 commented on cypress/support/e2e.js
> +// require('./commands'
end parenthesis missing

2024-08-19 09:07 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('[data-test="cart-list"]').should('contain', 'Sauce Labs Bolt T-Shirt','Sauce Labs Fleece Jacket','Test.allTheThings() T-Shirt (Red)','Sauce Labs Backpack')
The should('contain', ...) assertion in Cypress is typically used to check if an element contains a specific text string, but it only checks for one string at a time.
To check for multiple items in a list, you would need to write separate assertions for each item or use a different approach. Here's how you can do it:
cy.get('[data-test="cart-list"]').should('contain', 'Sauce Labs Bolt T-Shirt');
cy.get('[data-test="cart-list"]').should('contain', 'Sauce Labs Fleece Jacket');
cy.get('[data-test="cart-list"]').should('contain', 'Test.allTheThings() T-Shirt (Red)');
cy.get('[data-test="cart-list"]').should('contain', 'Sauce Labs Backpack');

2024-08-19 09:08 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#checkout').click();
Add assertions for button like it's text or visibility

2024-08-19 09:13 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#first-name').should('have.attr', 'placeholder', 'First Name');
line 145 and 146 can be combined and written in a single assertion chain like:
cy.get('#first-name')
   .should('be.visible')
   .and('be.enabled')
   .('have.attr', 'placeholder', 'First Name');

2024-08-19 09:13 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +
line 149 and 150 can be combined and written in a single assertion chain like:
cy.get('#last-name')
   .should('be.visible')
   .and('be.enabled')
   .('have.attr', 'placeholder', 'Last Name');

2024-08-19 09:14 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +
it's better to combine the lines 153 and 154 in a single assertion chain

2024-08-19 09:14 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +
it's better to combine the lines 156 and 157 in a single assertion chain

2024-08-19 09:14 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +
it's better to combine the lines 159 and 160 in a single assertion chain

2024-08-19 09:15 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#first-name').type('Rabeendra');
the line 163 can directly be used in the combination of 145 and 146 like:
cy.get('#first-name')
.should('be.visible')
.and('be.enabled')
.('have.attr', 'placeholder', 'First Name')
.type('Rabeendra');

2024-08-19 09:16 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#last-name').type('Gadel');
this can be used directly in the above line of last name assertion, to reduce the number of lines of  code

2024-08-19 09:16 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#postal-code').type('012345')
this can be used directly in the above line of last name assertion, to reduce the number of lines of  code

2024-08-19 09:17 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#cancel').should('have.text', 'Cancel');
line 76 and 177 can be combined in a single assertion.

2024-08-19 09:17 UTC, rtimalsina555 commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#finish').click();
line 178, 179 and 182 can be combined in a single assertion.

2024-08-19 09:19 UTC, rtimalsina555 requested changes
please make the necessary changes and send PR for review

2024-08-19 09:34 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get('#logout_sidebar_link').click();
yesko assertion maile aarko file maa garko xu tei vayera yesma nagareko

2024-08-19 09:37 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get('#react-burger-menu-btn').click();
login page ko assertion line 5- line 9 samma gareko xu tei vayera yaha nagareko ho....

2024-08-20 04:51 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#login-button").clear.click();
updated

2024-08-20 04:51 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#password").clear.type("secret_sauce");
updated

2024-08-20 04:51 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#user-name").clear.type("standard_user123");
updated

2024-08-20 04:51 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("#password").clear.type("secret_sauce123");
updated

2024-08-20 04:51 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +    it.skip('should not login with valid username and empty password', ()=>{
updated

2024-08-20 04:52 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +    it.skip('should not login with valid username and empty password', ()=>{
updated

2024-08-20 04:52 UTC, gadelrabee commented on cypress/e2e/swag_labs/loginTest.cy.js
> +        cy.get("input[name='login-button']").should('be.visible').and('not.be.disabled');
updated

2024-08-20 04:52 UTC, gadelrabee commented on cypress/support/e2e.js
> +// require('./commands'
updated

2024-08-20 04:52 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('[data-test="cart-list"]').should('contain', 'Sauce Labs Bolt T-Shirt','Sauce Labs Fleece Jacket','Test.allTheThings() T-Shirt (Red)','Sauce Labs Backpack')
updated

2024-08-20 04:52 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#checkout').click();
upated

2024-08-20 04:52 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#first-name').should('have.attr', 'placeholder', 'First Name');
updated

2024-08-20 04:52 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +
updated

2024-08-20 04:53 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +
updated

2024-08-20 04:53 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +
updated

2024-08-20 04:53 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +
updated

2024-08-20 04:53 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#first-name').type('Rabeendra');
updated

2024-08-20 04:53 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#last-name').type('Gadel');
updated

2024-08-20 04:53 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#continue').click();
updated

2024-08-20 04:54 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#postal-code').type('012345')
updated

2024-08-20 04:54 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#cancel').should('have.text', 'Cancel');
updated

2024-08-20 04:54 UTC, gadelrabee commented on cypress/e2e/swag_labs/add_to_cart.cy.js
> +        cy.get('#finish').click();
updated

2024-08-20 07:46 UTC, rtimalsina555 reviewed
All Good

2024-08-20 07:47 UTC, rtimalsina555 approved these changes

2024-08-20 07:54 UTC, Madhusudan-pandey approved these changes

2024-08-20 07:56 UTC, merged